version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
permissions:
  - object: /home/ubuntu/project
    owner: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: ubuntu